recursionDepth: 10
languages:
  - name: python3
    interpreter: /usr/bin/python3
    bang: "#!/usr/bin/python3"
    comment: "#"
    assignmentOperator: " = "
    flagEvaluateScript: "-c"
    fileExtension: ".py"
    execOpPrefix: "import os; os.system(\""
    execOpSuffix: "\")"
    correctErrLineNumber: true
    errLineNumberSymbol: "line"